[package]
name = "zcash-wasm-benchmark"
version = "0.1.0"
authors = ["eric"]
edition = "2018"

[lib]
crate-type = ["cdylib"]



[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[dependencies]
wasm-bindgen = "0.2.84"


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

zcash_note_encryption = "0.4.0"
orchard = { version = "0.7.0", default-feature = false }
getrandom = {version = "0.2.12", features = ["js"] }
web-sys = {version = "0.3.68", features = ["console"] }
rand = "0.8.5"
rayon = "1.8"
wasm-bindgen-rayon = {version = "1.2", features = ["no-bundler"], optional = true }
wasm-bindgen-futures = "0.4.41"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"


[features]
default = ["console_error_panic_hook"]
parallel = ["wasm-bindgen-rayon", "orchard/multicore"]